--- 
# Kubernetes configuration for Todo app with MongoDB
# This file defines the deployments and services for the Todo app and MongoDB using k3s.
#****************************************************************************************#

# MongoDB Deployment and Service
# This deployment runs 3 replicas of MongoDB and exposes it internally within the cluster.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1  # Run 1 MongoDB pods
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers: # container will be pulled from docker hub
        - name: mongo
          image: mongo:6
---
# MongoDB Service
# This service allows other pods to access MongoDB using the internal DNS name 'mongo'.
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
  clusterIP: None
---
# Todo App Deployment and Service
# This deployment runs 3 replicas of the Todo app and exposes it via a NodePort service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1  # Run 1 Todo app pods
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers: # This image is built and pushed to docker hub using github actions
        - name: todo
          image: mezozaki12/todo_app:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/todos
---
# Todo App Service
# This service exposes the Todo app on port 30080, allowing external access to the app
apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080
