#this is github action workflow file to build and publish a docker image to dockerhub
name: Build & publish image to docker hub

on:                         # run this workflow on the following events
   [workflow_dispatch]      # manual trigger
  
jobs:
  
   publish_image:
   
    runs-on: ubuntu-latest
   
    steps:

        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: build image
          run: docker build . -t mezozaki12/todo_list_project:latest

        
        - name: push image to dockerhub
          run: |
            docker login -u mezozaki12 -p ${{secrets.TODOIST_PROJECT}}
            docker push mezozaki12/todo_list_project:latest


       
