#this is github action workflow file to build and publish a docker image to dockerhub
name: Build & publish image to docker hub

on:
   [workflow_dispatch]
  
jobs:
  
   publish_image:
   
    runs-on: ubuntu-latest
   
    steps:

        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: build image
          run: docker build /home/mezozaki12/Desktop/Intern_Project/Todos-nodejs -t mezozaki12/todo_list_project:latest
        
        - name: push image to dockerhub
          run: |
            docker push mezozaki12/todo_list_project:latest


       
